name: flutter_app_kit_example
description: Minimal smoke example for flutter_app_kit.
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ^3.7.2
  flutter: ">=3.29.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_app_kit:
    path: ../
  lemsa_core_kit:
    path: ../../lemsa_core_kit

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^9.0.0

flutter:
  uses-material-design: true
